spring.application.name=ds

spring.output.ansi.enabled=ALWAYS

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://10.200.4.221:3306/jean_paulo_ds?createDatabaseIfNotExist=true
spring.datasource.username=jean_paulo
spring.datasource.password=eosguridogremio9

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
